#!/bin/bash

#SBATCH --job-name=roi-sub
#SBATCH --ntasks-per-node=1
#SBATCH --mem=4G
#SBATCH --time=00:15:00

set -x
set -e

time singularity exec -e docker://brainlife/fsl:5.0.11 ./fsl.sh

   
   
   
   
   
   
   
   
   
